package com.stone.study.model;

import java.io.Serializable;

public class UserRoleRelation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role_relation
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 4239074662857328253L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.id
     *
     * @return the value of user_role_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.id
     *
     * @param id the value for user_role_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.user_id
     *
     * @return the value of user_role_relation.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.user_id
     *
     * @param userId the value for user_role_relation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.role_id
     *
     * @return the value of user_role_relation.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.role_id
     *
     * @param roleId the value for user_role_relation.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}