package com.stone.study.mapper;

import com.stone.study.model.Func;
import com.stone.study.model.FuncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int countByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int deleteByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int insert(Func record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int insertSelective(Func record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    List<Func> selectByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    Func selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Func record, @Param("example") FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Func record, @Param("example") FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Func record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Func record);
}