package com.stone.study.mapper;

import com.stone.study.model.RoleFuncRelation;
import com.stone.study.model.RoleFuncRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleFuncRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int countByExample(RoleFuncRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int deleteByExample(RoleFuncRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int insert(RoleFuncRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int insertSelective(RoleFuncRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    List<RoleFuncRelation> selectByExample(RoleFuncRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    RoleFuncRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleFuncRelation record, @Param("example") RoleFuncRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleFuncRelation record, @Param("example") RoleFuncRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleFuncRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_func_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleFuncRelation record);
}